export const registry = [
  {
    name: 'accordion',
    description:
      'A vertically stacked set of interactive headings that each reveal a section of content.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-accordion'],
    registryDependencies: [],
    files: ['src/components/ui/accordion.tsx'],
  },
  {
    name: 'alert-dialog',
    description:
      'A modal dialog that interrupts the user with important content and expects a response.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-alert-dialog'],
    registryDependencies: [],
    files: ['src/components/ui/alert-dialog.tsx'],
  },
  {
    name: 'alert',
    description: 'Displays a callout for user attention.',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    files: ['src/components/ui/alert.tsx'],
  },
  {
    name: 'aspect-ratio',
    description: 'Displays content within a desired ratio.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-aspect-ratio'],
    registryDependencies: [],
    files: ['src/components/ui/aspect-ratio.tsx'],
  },
  {
    name: 'avatar',
    description: 'An image element with a fallback for representing the user.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-avatar'],
    registryDependencies: [],
    files: ['src/components/ui/avatar.tsx'],
  },
  {
    name: 'badge',
    description: 'Displays a badge or a component that looks like a badge.',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    files: ['src/components/ui/badge.tsx'],
  },
  {
    name: 'button',
    description: 'Displays a button or a component that looks like a button.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-slot'],
    registryDependencies: [],
    files: ['src/components/ui/button.tsx'],
  },
  {
    name: 'calendar',
    description: 'A date field component that allows users to enter and edit date.',
    type: 'registry:ui',
    dependencies: ['react-day-picker'],
    registryDependencies: ['button'],
    files: ['src/components/ui/calendar.tsx'],
  },
  {
    name: 'card',
    description: 'Displays a card with header, content, and footer.',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    files: ['src/components/ui/card.tsx'],
  },
  {
    name: 'carousel',
    description: 'A carousel component with motion support.',
    type: 'registry:ui',
    dependencies: ['embla-carousel-react'],
    registryDependencies: ['button'],
    files: ['src/components/ui/carousel.tsx'],
  },
  {
    name: 'checkbox',
    description: 'A control that allows the user to toggle between checked and not checked.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-checkbox'],
    registryDependencies: [],
    files: ['src/components/ui/checkbox.tsx'],
  },
  {
    name: 'collapsible',
    description: 'An interactive component which expands/collapses a panel.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-collapsible'],
    registryDependencies: [],
    files: ['src/components/ui/collapsible.tsx'],
  },
  {
    name: 'command',
    description: 'Fast, composable, unstyled command menu for React.',
    type: 'registry:ui',
    dependencies: ['cmdk'],
    registryDependencies: ['dialog'],
    files: ['src/components/ui/command.tsx'],
  },
  {
    name: 'context-menu',
    description: 'Displays a menu to the user — such as a set of actions or functions.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-context-menu'],
    registryDependencies: [],
    files: ['src/components/ui/context-menu.tsx'],
  },
  {
    name: 'dialog',
    description: 'A window overlaid on either the primary window or another dialog window.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-dialog'],
    registryDependencies: [],
    files: ['src/components/ui/dialog.tsx'],
  },
  {
    name: 'dropdown-menu',
    description: 'Displays a menu to the user — such as a set of actions or functions.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-dropdown-menu'],
    registryDependencies: [],
    files: ['src/components/ui/dropdown-menu.tsx'],
  },
  {
    name: 'hover-card',
    description: 'For sighted users to preview content available behind a link.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-hover-card'],
    registryDependencies: [],
    files: ['src/components/ui/hover-card.tsx'],
  },
  {
    name: 'input',
    description: 'Displays a form input field or a component that looks like an input field.',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    files: ['src/components/ui/input.tsx'],
  },
  {
    name: 'label',
    description: 'Renders an accessible label associated with controls.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-label'],
    registryDependencies: [],
    files: ['src/components/ui/label.tsx'],
  },
  {
    name: 'menubar',
    description: 'A visually persistent menu common in desktop applications.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-menubar'],
    registryDependencies: [],
    files: ['src/components/ui/menubar.tsx'],
  },
  {
    name: 'navigation-menu',
    description: 'A collection of links for navigating websites.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-navigation-menu'],
    registryDependencies: [],
    files: ['src/components/ui/navigation-menu.tsx'],
  },
  {
    name: 'popover',
    description: 'Displays rich content in a portal, triggered by a button.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-popover'],
    registryDependencies: [],
    files: ['src/components/ui/popover.tsx'],
  },
  {
    name: 'progress',
    description: 'Displays an indicator showing the completion progress of a task.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-progress'],
    registryDependencies: [],
    files: ['src/components/ui/progress.tsx'],
  },
  {
    name: 'radio-group',
    description: 'A set of checkable buttons—known as radio buttons.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-radio-group'],
    registryDependencies: [],
    files: ['src/components/ui/radio-group.tsx'],
  },
  {
    name: 'scroll-area',
    description: 'Augments native scroll functionality for custom, cross-browser styling.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-scroll-area'],
    registryDependencies: [],
    files: ['src/components/ui/scroll-area.tsx'],
  },
  {
    name: 'select',
    description: 'Displays a list of options for the user to pick from—triggered by a button.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-select'],
    registryDependencies: [],
    files: ['src/components/ui/select.tsx'],
  },
  {
    name: 'separator',
    description: 'A visual separator between different content or sections.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-separator'],
    registryDependencies: [],
    files: ['src/components/ui/separator.tsx'],
  },
  {
    name: 'sheet',
    description:
      'Extends the Dialog component to display content that complements the main content of the screen.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-dialog'],
    registryDependencies: [],
    files: ['src/components/ui/sheet.tsx'],
  },
  {
    name: 'slider',
    description: 'An input where the user selects a value from within a given range.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-slider'],
    registryDependencies: [],
    files: ['src/components/ui/slider.tsx'],
  },
  {
    name: 'switch',
    description: 'A toggle switch alternative to the checkbox.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-switch'],
    registryDependencies: [],
    files: ['src/components/ui/switch.tsx'],
  },
  {
    name: 'table',
    description: 'A responsive table component.',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    files: ['src/components/ui/table.tsx'],
  },
  {
    name: 'tabs',
    description: 'A set of layered sections of content—known as tab panels.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-tabs'],
    registryDependencies: [],
    files: ['src/components/ui/tabs.tsx'],
  },
  {
    name: 'textarea',
    description: 'Displays a form textarea or a component that looks like a textarea.',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    files: ['src/components/ui/textarea.tsx'],
  },
  {
    name: 'toggle',
    description: 'A two-state button that can be either on or off.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-toggle'],
    registryDependencies: [],
    files: ['src/components/ui/toggle.tsx'],
  },
  {
    name: 'toggle-group',
    description: 'A set of two-state buttons that can be toggled on or off.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-toggle-group'],
    registryDependencies: [],
    files: ['src/components/ui/toggle-group.tsx'],
  },
  {
    name: 'tooltip',
    description:
      'A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-tooltip'],
    registryDependencies: [],
    files: ['src/components/ui/tooltip.tsx'],
  },
]
